language: php

php:
  - nightly

install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover coverage_clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
